Removed `laminas/laminas-zendframework-bridge` as dependency
laminas-api-tools/api-tools-versioning pull request #13
Opened 2022-06-27 13:40 UTC by fabiang

Imho projects that require the bridge should require `laminas/laminas-zendframework-bridge` in their root composer.json. 

Currently having this as an indirect dependency otherwise triggers error when using Psalm under PHP 8.1. It looks like I'm not the only one having this issue and I wasn't able to deep dive what the real issue is here (so possible upstream bug).

> ./vendor/bin/psalm --report=reports/psalm.txt --show-info=true --config=psalm.xml
Target PHP version: 8.1 (inferred from composer.json)
Scanning files...
PHP Fatal error:  Trait "Laminas\Db\Adapter\AdapterAwareTrait" not found in vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27
Fatal error: Trait "Laminas\Db\Adapter\AdapterAwareTrait" not found in vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27
script returned exit code 255

2022-06-27 15:59 UTC, boesing commented
We already discussed that in one of the TSC meetings and started to remove the dependency in several components.

Please have a look at the minutes of that meeting to provide a proper patch:

https://github.com/laminas/technical-steering-committee/blob/57d650803645853bf0f00de0ac41cc8ffe28d36b/meetings/minutes/2021-08-02-TSC-Minutes.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages

2022-06-27 17:53 UTC, Ocramius commented
Note: as for removing the bridge, we're all for it, but it was introduced for BC compliance, and it needs to be removed in a BC compliant way.

To remove it, follow @boesing's link for the correct approach 👍

2022-06-28 08:14 UTC, fabiang commented
Working on it 🫡

2022-06-28 08:19 UTC, fabiang commented
Updated and squashed.

2022-06-28 09:10 UTC, Ocramius requested changes

2022-06-28 09:10 UTC, Ocramius commented on composer.json
> +        "laminas/laminas-stdlib": "^2.7.7 || ^3.0.1"
I think `composer.lock` got updated with a newer PHP version.

Two solutions here:

 1. drop PHP 7.3 support
 2. re-generate `composer.lock` after having configured `config.platform.php: 7.3.99`

2022-06-28 11:23 UTC, boesing commented
Yah, `composer.lock` to be generated with the lowest PHP version supported by a component.
In this case, PHP 7.3

2022-06-28 11:33 UTC, fabiang commented
Updated the `composer.lock` under PHP 7.3.

2022-06-28 15:17 UTC, Ocramius commented
Some minor unrelated adjustments needed (things that changed in CI dependencies).

I'll take care of them while merging, meanwhile thanks, @fabiang! :+1:

2022-06-28 15:37 UTC, merged

2022-06-28 15:37 UTC, Ocramius commented
:ship:

2022-06-29 08:41 UTC, fabiang commented
Thank you for your efforts!

2022-06-29 08:47 UTC, Ocramius commented
@fabiang thank YOU for spotting and fixing this. Please feel free to send any more of these if you still spot `laminas/laminas-zendframework-bridge` in the wild